eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # 注册到 eureka
server:
  port: 8762
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411   # 注册到 zipkin
  sleuth:
    sampler:
      percentage: 1.0   # 即以 100% 的概率将链路的数据上传给 Zipkin Server，在默认情况下，该值为0.1。

#spring.zipkin.base-url=http://localhost:9411
