---
spring:
   profiles: peer1
server:
   port: 8761
eureka:
   instance:
      hostname: peer1  #1、在实际开发中，是具体的服务器 地址，修改host
   client:
      serviceUrl:
         defaultZone: http://peer2:8762/eureka/  # 2、相互注册，然后有一个客户端随便注册到其中某一个eureka中，就等同于两个eureka都有注册这个客户端


---

spring:
   profiles: peer2
server:
   port: 8762
eureka:
   instance:
      hostname: peer2  #1、在实际开发中，是具体的服务器 地址，修改host
   client:
      serviceUrl:
         defaultZone: http://peer1:8761/eureka/  # 2、相互注册，然后有一个客户端随便注册到其中某一个eureka中，就等同于两个eureka都有注册这个客户端
