# native

#spring:
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared
#  profiles:
#     active: native
#  application:
#    name: config-server

server:
  port: 8769

# remote git
spring:
  cloud:
    config:
      server:    #这个配置指明仓库的地址，可以是git上的，也可以是本地的，本地的参照上面的
        git:
          uri: https://github.com/chenquan1992/SpringCloudConfig
          searchPaths: src/shared   #serachPaths 为搜索远程仓库的文件夹地址，
          username:
          password:
      label: master  #label 为git 库的分支名
  application:
    name: config-server