eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 5000
spring:
  application:
    name: service-zuul
zuul:
  routes:
    hiapi:     #随便填的，一种标识
      path: /hiapi/**    # 请求这个路径的时候，zuul会自动将请求路由， Zuul 在路由转发也是有做了负载均衡的
      serviceId: eureka-client  # 到名字为 eureka-client 的微服务中
#      url: http://localhost:8762  #这样写不会做负载均衡
#      serviceId: hiapi-v1
    ribbonapi:
      path: /ribbonapi/**
      serviceId: eureka-ribbon-client
    feignapi:
      path: /feignapi/**
      serviceId: eureka-feign-client
#      stripPrefix: false  有该字段，请求的"feignapi"会被转发到
#zuul.prefix: /v1  #加个前缀
#ribbon:
#  eureka:
#    enabled: false
#
#hiapi-v1:
#  ribbon:
#    listOfServers: http://localhost:8762,http://localhost:8763

#需求都请求来到网关zuul，再由zuul路由到其他的微服务，其实在api接口中就已经知道要请求到哪个微服务了