spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared      #Spring cloud的配置文件所在地，供其他服务请求获取配置文件
  profiles:
     active: native
  application:
    name: config-server

server:
  port: 8769


