# native

#spring:
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared
#  profiles:
#     active: native
#  application:
#    name: config-server

server:
  port: 8768

# remote git
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenquan1992/SpringCloudConfig
          searchPaths: src/shared   #serachPaths 为搜索远程仓库的文件夹地址，
          username: 
          password:
      label: master
  application:
    name: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/